url: https://ZoraCyber.github.io
baseurl: /RepairGal/

# Site settings
title: RepairGal eShop
email: RepairGal@protonmail.com
description: "RepairGal, woman run international console/electronical device repair, and modding services based in Ontario Canada."


# Team names, titles and social links
people:
- name: Zora Cyber
  pic: Cute_Profile
  position: Lead Repair Technician & Owner
  social:
    - title: github
      url: https://github.com/ZoraCyber
      

# Postal address (add as many lines as necessary)
address:
  - line: Made with ❤️ from Ontario, Canada.
# Build settings
markdown: kramdown
permalink: pretty
